<?php

/** @var \Api\V1\Entity\Sender $sender */
$sender = $this->sender;
$this->subject = $sender->getFullName() . ' sent you an IWITNESS E-Gift! - E-Gift Redeemable at IWITNESS.com';

/** @var \Api\V1\Entity\GiftCard $giftCard */
$giftCard = $this->giftCard;
$start_date = $this->startdate;

?>

<div class="table-responsive">
    <table width="100%" style="background-color:#fafafa !important;" class="header">
        <tr>
            <td style="padding:20px;">
                <table>
                    <tr>
                        <td style="padding-right:40px;">
                            <h1 style="border-bottom:1px solid #777777;" class="red">SOMEONE WANTS TO KEEP YOU SAFE</h1>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h3 style="color:#777777;">
                                You have received an iWitness E-Gift.
                                <br>
                                <a style="color:#777777;"
                                   href="<?= $this->baseUrl ?>/claim-code?code=<?= $giftCard->getCode() ?>">Click
                                    here</a> to redeem.
							</h3>
                            <p style="font-size:16px;">
                              Gift Card Date: <?= $start_date ?>
							</p>
                            <p style="font-size:16px;">
							 Valid upto 1 year</p>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <p style="font-size:16px;">
								With Best Compliments From <b><?= $sender->getFirstName() ?></b> To  <b><?= $giftCard->getName()?></b>
                            </p>
                        </td>
                    </tr>
                </table>
            </td>
            <td width="30%" style="text-align:left;">
                <img
                    class="img-responsive" width="100%"
                    src="<?= $this->apiBaseUrl ?>/images/2.0/phone.jpg"
                    alt="iWitness.com"/>
            </td>
        </tr>
    </table>

    <table width="100%" class="red-bottom">
        <tr>
            <td width="50%" style="padding:20px;">
                <?php if (!empty($giftCard->getMessage())): ?>
                    <p>
                        <?= nl2br($giftCard->getMessage()) ?>
                    </p>
                <?php else: ?>
                    <p>
                        <?= $giftCard->getName() ?>,
                    </p>
                    <p>
                        Please use this app to stay safe wherever you go, especially when you're alone.
                    </p>
                <?php endif; ?>
            </td>
            <td width="50%" style="background-color:#dcdee1 !important; padding:20px;">
                <table width="100%" style=" border-bottom:1px solid #777777; margin-bottom:5px;">
                    <tr>
						<td>
                            <h1 class="red" style="text-align:justify">
                                ONE YEAR
							</h1>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h3 class="red" style="text-align:justify">
                                GIFT SUBSCRIPTION
                            </h3>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding-top:5px;">
                            <a class="btn btn-primary" style="width:100%; font-size:22px"
                               href="<?= $this->baseUrl ?>/claim-code?code=<?= $giftCard->getCode() ?>">
                                Redeem Now
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding:5px 10px;">
                            Claim Code:
                            <br>
                            <span class="red"><?= $giftCard->getCode() ?></span>
                        </td>
                    </tr>
                </table>
                <table class="instructions">
                    <tr>
                        <td>
                            <p>Redeeming your iWitness E-Gift is easy:</p>
                            <ol>
                                <li>Visit our Web site at
                                    <a href="<?= $this->baseUrl ?>/claim-code"><?= $this->baseUrl ?></a>
                                </li>
                                <li>Enter your claim code.</li>
                                <li>Activate and set up your account.</li>
                            </ol>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

    <table width="100%" style="border-bottom:30px solid #77787b">
        <tr>
            <td style="text-align:left; padding: 10px 20px 0 20px; border: 0px; line-height:1.2" class="sub-header">
                <div>
                    <p>
                        <strong>ABOUT IWITNESS</strong>
                        <br>
                        iWitness turns your smartphone into the one thing criminals fear most - a witness to their
                        acitons.
                    </p>
                </div>
            </td>
        </tr>
        <tr style="background-color:#bebec0; text-align:center; ">
            <td>
                <a href="<?= $this->baseUrl ?>/content-how-it-works">
                    <img
                        class="img-responsive" width="100%"
                        src="<?= $this->apiBaseUrl ?>/images/2.0/how-it-works.jpg"
                        alt="Learn how iWitness works at <?= $this->baseUrl ?>"/>
                </a>
            </td>
        </tr>
    </table>
</div>

<?= $this->render('partial/common-sense.phtml') ?>
