<?php

namespace DoctrineORMModule\Proxy\__CG__\Api\V1\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Admin extends \Api\V1\Entity\Admin implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getResourceId()
    {
        $this->__load();
        return parent::getResourceId();
    }

    public function isAdmin()
    {
        $this->__load();
        return parent::isAdmin();
    }

    public function getSubscriptionId()
    {
        $this->__load();
        return parent::getSubscriptionId();
    }

    public function setSubscriptionId($subscriptionId)
    {
        $this->__load();
        return parent::setSubscriptionId($subscriptionId);
    }

    public function getSubscriptionStartAt()
    {
        $this->__load();
        return parent::getSubscriptionStartAt();
    }

    public function setSubscriptionStartAt($subscriptionStartAt)
    {
        $this->__load();
        return parent::setSubscriptionStartAt($subscriptionStartAt);
    }

    public function getSubscriptionExpireAt()
    {
        $this->__load();
        return parent::getSubscriptionExpireAt();
    }

    public function setSubscriptionExpireAt($subscriptionExpireAt)
    {
        $this->__load();
        return parent::setSubscriptionExpireAt($subscriptionExpireAt);
    }

    public function getSubscriptionLastEmail()
    {
        $this->__load();
        return parent::getSubscriptionLastEmail();
    }

    public function setSubscriptionLastEmail($subscriptionLastEmail)
    {
        $this->__load();
        return parent::setSubscriptionLastEmail($subscriptionLastEmail);
    }

    public function getContacts()
    {
        $this->__load();
        return parent::getContacts();
    }

    public function addContacts($contact)
    {
        $this->__load();
        return parent::addContacts($contact);
    }

    public function removeContacts($contact)
    {
        $this->__load();
        return parent::removeContacts($contact);
    }

    public function getExpireInDay()
    {
        $this->__load();
        return parent::getExpireInDay();
    }

    public function hasExpired()
    {
        $this->__load();
        return parent::hasExpired();
    }

    public function getSubscriptions()
    {
        $this->__load();
        return parent::getSubscriptions();
    }

    public function addSubscriptions(\Doctrine\Common\Collections\ArrayCollection $subscriptions)
    {
        $this->__load();
        return parent::addSubscriptions($subscriptions);
    }

    public function removeSubscriptions(\Doctrine\Common\Collections\ArrayCollection $subscriptions)
    {
        $this->__load();
        return parent::removeSubscriptions($subscriptions);
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getPhone()
    {
        $this->__load();
        return parent::getPhone();
    }

    public function setPhone($phone)
    {
        $this->__load();
        return parent::setPhone($phone);
    }

    public function getPhoneAlt()
    {
        $this->__load();
        return parent::getPhoneAlt();
    }

    public function setPhoneAlt($phoneAlt)
    {
        $this->__load();
        return parent::setPhoneAlt($phoneAlt);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFullName()
    {
        $this->__load();
        return parent::getFullName();
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getAddress1()
    {
        $this->__load();
        return parent::getAddress1();
    }

    public function setAddress1($address1)
    {
        $this->__load();
        return parent::setAddress1($address1);
    }

    public function getAddress2()
    {
        $this->__load();
        return parent::getAddress2();
    }

    public function setAddress2($address2)
    {
        $this->__load();
        return parent::setAddress2($address2);
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function setCity($city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setState($state)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getZip()
    {
        $this->__load();
        return parent::getZip();
    }

    public function setZip($zip)
    {
        $this->__load();
        return parent::setZip($zip);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getBirthDate()
    {
        $this->__load();
        return parent::getBirthDate();
    }

    public function setBirthDate($birthDate)
    {
        $this->__load();
        return parent::setBirthDate($birthDate);
    }

    public function getHeightFeet()
    {
        $this->__load();
        return parent::getHeightFeet();
    }

    public function setHeightFeet($heightFeet)
    {
        $this->__load();
        return parent::setHeightFeet($heightFeet);
    }

    public function getHeightInches()
    {
        $this->__load();
        return parent::getHeightInches();
    }

    public function setHeightInches($heightInches)
    {
        $this->__load();
        return parent::setHeightInches($heightInches);
    }

    public function getWeight()
    {
        $this->__load();
        return parent::getWeight();
    }

    public function setWeight($weight)
    {
        $this->__load();
        return parent::setWeight($weight);
    }

    public function getEyeColor()
    {
        $this->__load();
        return parent::getEyeColor();
    }

    public function setEyeColor($eyeColor)
    {
        $this->__load();
        return parent::setEyeColor($eyeColor);
    }

    public function getHairColor()
    {
        $this->__load();
        return parent::getHairColor();
    }

    public function setHairColor($hairColor)
    {
        $this->__load();
        return parent::setHairColor($hairColor);
    }

    public function getEthnicity()
    {
        $this->__load();
        return parent::getEthnicity();
    }

    public function setEthnicity($ethnicity)
    {
        $this->__load();
        return parent::setEthnicity($ethnicity);
    }

    public function getDistFeature()
    {
        $this->__load();
        return parent::getDistFeature();
    }

    public function setDistFeature($distFeature)
    {
        $this->__load();
        return parent::setDistFeature($distFeature);
    }

    public function getPhoto()
    {
        $this->__load();
        return parent::getPhoto();
    }

    public function setPhoto($photo)
    {
        $this->__load();
        return parent::setPhoto($photo);
    }

    public function getTimezone()
    {
        $this->__load();
        return parent::getTimezone();
    }

    public function setTimezone($timezone)
    {
        $this->__load();
        return parent::setTimezone($timezone);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function getFlags()
    {
        $this->__load();
        return parent::getFlags();
    }

    public function setFlags($flags)
    {
        $this->__load();
        return parent::setFlags($flags);
    }

    public function getSecretKey()
    {
        $this->__load();
        return parent::getSecretKey();
    }

    public function setSecretKey($secretKey)
    {
        $this->__load();
        return parent::setSecretKey($secretKey);
    }

    public function toggleSuspended()
    {
        $this->__load();
        return parent::toggleSuspended();
    }

    public function isSuspended()
    {
        $this->__load();
        return parent::isSuspended();
    }

    public function setDeleted($deleted)
    {
        $this->__load();
        return parent::setDeleted($deleted);
    }

    public function isDeleted()
    {
        $this->__load();
        return parent::isDeleted();
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function getModified()
    {
        $this->__load();
        return parent::getModified();
    }

    public function setModified($modified)
    {
        $this->__load();
        return parent::setModified($modified);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'phone', 'phoneAlt', 'firstName', 'lastName', 'address1', 'address2', 'city', 'state', 'zip', 'email', 'gender', 'birthDate', 'heightFeet', 'heightInches', 'weight', 'eyeColor', 'hairColor', 'ethnicity', 'distFeature', 'photo', 'timezone', 'password', 'flags', 'secretKey', 'deleted', 'created', 'modified', 'subscriptions', 'subscriptionId', 'subscriptionStartAt', 'subscriptionExpireAt', 'subscriptionLastEmail', 'contacts');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}