<?php

namespace DoctrineORMModule\Proxy\__CG__\Api\V1\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Event extends \Api\V1\Entity\Event implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getInitialLat()
    {
        $this->__load();
        return parent::getInitialLat();
    }

    public function setInitialLat($initialLat)
    {
        $this->__load();
        return parent::setInitialLat($initialLat);
    }

    public function getInitialLong()
    {
        $this->__load();
        return parent::getInitialLong();
    }

    public function setInitialLong($initialLong)
    {
        $this->__load();
        return parent::setInitialLong($initialLong);
    }

    public function getProcessed()
    {
        $this->__load();
        return parent::getProcessed();
    }

    public function setProcessed($processed)
    {
        $this->__load();
        return parent::setProcessed($processed);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setUser(\Api\V1\Entity\User $user = NULL)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getLog()
    {
        $this->__load();
        return parent::getLog();
    }

    public function addLog($message)
    {
        $this->__load();
        return parent::addLog($message);
    }

    public function getAssets()
    {
        $this->__load();
        return parent::getAssets();
    }

    public function addAssets(\Doctrine\Common\Collections\ArrayCollection $assets)
    {
        $this->__load();
        return parent::addAssets($assets);
    }

    public function removeAssets(\Doctrine\Common\Collections\ArrayCollection $assets)
    {
        $this->__load();
        return parent::removeAssets($assets);
    }

    public function getResourceId()
    {
        $this->__load();
        return parent::getResourceId();
    }

    public function getFlags()
    {
        $this->__load();
        return parent::getFlags();
    }

    public function setFlags($flags)
    {
        $this->__load();
        return parent::setFlags($flags);
    }

    public function getAttempted()
    {
        $this->__load();
        return parent::getAttempted();
    }

    public function increaseAttempted()
    {
        $this->__load();
        return parent::increaseAttempted();
    }

    public function getAssetIds()
    {
        $this->__load();
        return parent::getAssetIds();
    }

    public function getAssetGps()
    {
        $this->__load();
        return parent::getAssetGps();
    }

    public function newAssetProcessed()
    {
        $this->__load();
        return parent::newAssetProcessed();
    }

    public function isDeleted()
    {
        $this->__load();
        return parent::isDeleted();
    }

    public function setDeleted($deleted)
    {
        $this->__load();
        return parent::setDeleted($deleted);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function getModified()
    {
        $this->__load();
        return parent::getModified();
    }

    public function setModified($modified)
    {
        $this->__load();
        return parent::setModified($modified);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'initialLat', 'initialLong', 'processed', 'name', 'log', 'flags', 'attempted', 'deleted', 'created', 'modified', 'user', 'assets');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}