<?php
 $this->subject = $this->user->getFirstName() . ' - Your subscription to iWitness was expired in '.gmdate("Y-m-d", $this->user->getSubscriptionLastEmail()).'.';
?>

<div class="body">
    <p>
        <?= $this->escapeHtml($this->user->getFirstName()) ?>...
    </p>
    <p>
        Please log-in and renew your membership at:
        <a href="<?= $this->baseUrl.'/renew' ?>"><?= $this->baseUrl.'/renew' ?></a>
    </p>



    <p>
        Your team at iWitness.
    </p>

    <p>
        Learn more about <a href="<?= $this->baseUrl ?>/content-how-it-works">how it works</a>.
    </p>
</div>
