<?php
$this->subject = 'Reset password';
$to = $this->to;
$resetUrl = $this->baseUrl.'/reset-password';
$resetUrl .= '?t=' . $token;



?>
<div class="body">
    <h1>Reset Password</h1>
    <p>
        Hello <?= $to->getFirstName() ?> <?= $to->getLastName() ?>,<br/>
        <br/>
        To reset your password - please visit <a href="<?= $resetUrl ?>">this link</a>.
    </p>
    <p>
        Note: this link will expire in <?= $this->expireHours ?> hours.
    </p>
</div>