<?php
$this->subject = $this->firstName . ' ' . $this->lastName . ' wants you to protect yourself.';
?>


<div class="body">
    <p>
        Hi<?= !empty($this->name) ? ' ' . htmlentities($this->name) : '' ?>,
    </p>

    <?php if (!empty($this->message)): ?>
        <p>
            <?= nl2br($this->message) ?>
        </p>
    <?php else: ?>
        <p>
            I've just started using the iWitness app to stay safe.
            <br>
            You should check it out too.
        </p>
    <?php endif; ?>

    <p>
        <a href="mailto:<?= $this->email ?>">
            <strong>
                <?= $this->firstName ?> <?= $this->lastName ?>
            </strong>
        </a>
    </p>
</div>

<div class="table-responsive">
    <table width="100%" style="border-bottom:30px solid #77787b">
        <tr>
            <td style="text-align:left; padding: 10px 20px 0 20px; border: 0px; line-height:1.2;" class="sub-header">
                <div>
                    <p>
                        <strong>ABOUT IWITNESS</strong>
                        <br>
                        iWitness turns your smartphone into the one thing criminals fear most - a witness to their
                        actions.
                    </p>
                </div>
            </td>
        </tr>
        <tr style="background-color:#bebec0; text-align:center; ">
            <td>
                <a href="<?= $this->baseUrl ?>/content-how-it-works">
                    <img
                        class="img-responsive" width="100%"
                        src="<?= $this->apiBaseUrl ?>/images/2.0/how-it-works2.jpg"
                        alt="Learn how iWitness works at <?= $this->baseUrl ?>"/>
                </a>
            </td>
        </tr>
    </table>
    <table>
        <tr>
            <td style="text-align:left; padding: 20px 20px 10px 20px; border: 0; line-height:1.6">
                <div>
                    <p>
                        Protect Yourself.
                        <br/>
                        <a class="btn btn-primary" style="font-size:20px" href="<?= $this->baseUrl ?>">GET IWITNESS</a>
                    </p>
                </div>
            </td>
        </tr>
    </table>
</div>