<div class="body">
    <p>
        <strong>
            Common Sense Protection
        </strong>
    <p>
    <p>
        Everyone knows that it’s safer to walk with others than by yourself. But the truth is... there are times
        every day when you ARE alone. The question is... how will you stay safe?
    </p>
    <p>
        iWitness is the personal safety app for smartphones that can provide you with an extra layer of
        safety whenever you want one.
    </p>
    <p>
        Wherever you are, you can open and arm iWitness in seconds to start capturing video and audio of your
        surroundings and sending it to a secure off-premises server location, along with your real-time GPS location.
        Once sent, this data cannot be recalled, reversed, or undone in any way by a perpetrator.
    </p>
    <p>
        If you encounter a person or situation that makes you feel unsafe, simply tap the screen to put iWitness
        into Emergency Mode. It will then automatically dial 911, notify your trusted contacts that you feel
        endangered, and sound an alarm.
    </p>
</div>
